### ISSUE TITLE
Viaplay

### ISSUE THREAD

**Issue by adamosborne83** [Fourqui/tv#2]
**What logo would you like to see?**
Viaplay

**In what country is the channel shown?**
Uk and ireland

**Links to some version of the logo or the website for the channel(optional)**
Link: 

**Additional information(optional)**
Thank you so much

**Comment by le4689** [comment]
Links:
https://static.wikia.nocookie.net/logopedia/images/5/5c/Viaplay_Sports_1.svg
https://static.wikia.nocookie.net/logopedia/images/f/fc/Viaplay_Sports_2.svg
https://static.wikia.nocookie.net/logopedia/images/5/59/Viaplay_Xtra.svg
